/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica1nb;

import java.awt.Color;

/**
 *
 * @author 52552
 */
public class OpRandom extends javax.swing.JFrame {

    /** Creates new form OpRandom */
    public OpRandom() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        num1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        den1 = new javax.swing.JLabel();
        den2 = new javax.swing.JLabel();
        num2 = new javax.swing.JLabel();
        op1 = new javax.swing.JLabel();
        resden1 = new javax.swing.JTextField();
        resnum1 = new javax.swing.JTextField();
        comprobar1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comprobar4 = new javax.swing.JButton();
        comprobar2 = new javax.swing.JButton();
        comprobar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Operaciones Aleatorias");

        num1.setBackground(new java.awt.Color(255, 255, 255));
        num1.setOpaque(true);
        num1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                num1ComponentShown(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("=");
        jLabel4.setOpaque(true);

        den1.setBackground(new java.awt.Color(255, 255, 255));
        den1.setOpaque(true);

        den2.setBackground(new java.awt.Color(255, 255, 255));
        den2.setOpaque(true);

        num2.setBackground(new java.awt.Color(255, 255, 255));
        num2.setOpaque(true);

        op1.setBackground(new java.awt.Color(255, 255, 255));
        op1.setOpaque(true);

        resnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resnum1ActionPerformed(evt);
            }
        });

        comprobar1.setLabel("Comprobar");
        comprobar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobar1ActionPerformed(evt);
            }
        });

        comprobar4.setText("Nueva Operación");
        comprobar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobar4ActionPerformed(evt);
            }
        });

        comprobar2.setText("Borrar todo");
        comprobar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobar2ActionPerformed(evt);
            }
        });

        comprobar3.setText("Salir");
        comprobar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comprobar4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(den1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(den2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resden1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 129, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(comprobar1)
                        .addGap(18, 18, 18)
                        .addComponent(comprobar2)
                        .addGap(18, 18, 18)
                        .addComponent(comprobar3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(270, 270, 270)
                    .addComponent(op1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(472, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(comprobar4)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(den1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(den2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(resnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resden1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comprobar1)
                    .addComponent(comprobar2)
                    .addComponent(comprobar3))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addComponent(op1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(171, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    //La operacion es global 
    
    Operacion OpAle= new Operacion();
    //Commbruba el resultado
    private void comprobar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobar1ActionPerformed
 
        if(resnum1.getText()!="" && resden1.getText()!=""){
           Racional resultadoU = new Racional();
           resultadoU.setNumerador(Integer.parseInt(resnum1.getText()));
           resultadoU.setDenominador(Integer.parseInt(resden1.getText()));
           resultadoU.simpRacional();
           resultadoU.imprimir();
           if(OpAle.resultado.equalsRacional(resultadoU)){
               resnum1.setBackground(Color.green);
               resden1.setBackground(Color.green);
               System.out.println("El resultado es correcto ¡Felicidades!");
               System.out.println("Resultado Simplicado= ");
               OpAle.resultado.imprimir();
           }
           else{
                resnum1.setBackground(Color.red);
                resden1.setBackground(Color.red);
                System.out.println("El resultado correcto es= " );
                OpAle.resultado.imprimir();
           }
       }
    }//GEN-LAST:event_comprobar1ActionPerformed

    private void num1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_num1ComponentShown
      
    }//GEN-LAST:event_num1ComponentShown
    //Esta funcion genera los numeros aleatorios
    private void comprobar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobar4ActionPerformed
        
        num1.setText(Integer.toString(OpAle.num1.getNumerador()));
        den1.setText(Integer.toString(OpAle.num1.getDenominador()));
        num2.setText(Integer.toString(OpAle.num2.getNumerador()));
        den2.setText(Integer.toString(OpAle.num2.getDenominador()));
        op1.setText(Character.toString(OpAle.operador));
        //generamos el resultado
        OpAle.calculadora();
        
 
    }//GEN-LAST:event_comprobar4ActionPerformed

    private void resnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resnum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resnum1ActionPerformed

    private void comprobar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobar2ActionPerformed
        num1.setText("");
        den1.setText("");
        num2.setText("");
        den2.setText("");
        op1.setText("");
        resnum1.setText("");
        resden1.setText("");
        resnum1.setBackground(Color.white);
        resden1.setBackground(Color.white);
    }//GEN-LAST:event_comprobar2ActionPerformed

    private void comprobar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobar3ActionPerformed
     
        System.exit(0);
    }//GEN-LAST:event_comprobar3ActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpRandom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpRandom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpRandom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpRandom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpRandom().setVisible(true);
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comprobar1;
    private javax.swing.JButton comprobar2;
    private javax.swing.JButton comprobar3;
    private javax.swing.JButton comprobar4;
    private javax.swing.JLabel den1;
    private javax.swing.JLabel den2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel num1;
    private javax.swing.JLabel num2;
    private javax.swing.JLabel op1;
    private javax.swing.JTextField resden1;
    private javax.swing.JTextField resnum1;
    // End of variables declaration//GEN-END:variables

}
